name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  npm:
    runs-on: ubuntu-slim
    steps:
    - uses: actions/checkout@v6
    - run: npm ci --ignore-scripts
    - run: npm run prepare

    - name: Publish to npm
      run: |
        [[ "$GITHUB_REF_NAME" =~ - ]] && npm config set tag=next
        npm pkg set version="${GITHUB_REF_NAME/v/}"
        npm publish --ignore-scripts
    - name: Publish to JSR
      run: npx deno publish --allow-dirty --set-version="${GITHUB_REF_NAME/v/}"
